name: "Jinja2Config"
description: "Compile Home Assistant config files from Jinja2 templates"
version: "1.0.4"
slug: "jinja2config"
init: false
map:
  - config:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  log_level: debug
  config_dir: "/config"
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  config_dir: str
